wallpaper {
    monitor =
    path = /home/yogipatel/Pictures/Wallpapers/976013.jpg
    fit_mode = cover
}

preload = /home/yogipatel/Pictures/Wallpapers/berserk_dark.jpg
wallpaper = ,/home/yogipatel/Pictures/Wallpapers/berserk_dark.jpg
