wallpaper {
    monitor =
    path = /home/yogipatel/Pictures/Wallpapers/wp14912838-one-piece-4k-dark-wallpapers.webp
    fit_mode = cover
}

preload = /home/yogipatel/Pictures/Wallpapers/wp14912838-one-piece-4k-dark-wallpapers.webp
wallpaper = ,/home/yogipatel/Pictures/Wallpapers/wp14912838-one-piece-4k-dark-wallpapers.webp

